[package]
name = "aurora-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine = { git = "https://github.com/aurora-is-near/aurora-engine.git", version = "2.7" }
aurora-engine-sdk = { git = "https://github.com/aurora-is-near/aurora-engine.git", version = "1" }
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", version = "1" }
borsh = { version = "0.9.3", default-features = false }
lazy_static = "1.4.0"
thiserror = "1.0.35"
workspaces = { git = "https://github.com/aurora-is-near/workspaces-rs.git", version = "0.5" }
