[package]
name = "aurora-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "c8131a97a07916590343d8fe8d8fc7a4c34e6643",  features = ["impl-serde"] }
aurora-engine-sdk = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "c8131a97a07916590343d8fe8d8fc7a4c34e6643" }
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "c8131a97a07916590343d8fe8d8fc7a4c34e6643",  features = ["impl-serde"] }
borsh = { version = "0.9.3", default-features = false }
ethereum-types = "0.13.1"
lazy_static = "1.4.0"
near-account-id = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.35"
workspaces = { git = "https://github.com/aurora-is-near/workspaces-rs.git", version = "0.5" }
