[package]
name = "mock_evm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.1.0-pre.3"
aurora-workspace = { path = "../..", features = ["mock"] }
workspaces = "0.5.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
