[package]
name = "aurora-workspace-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum-types = { version = "0.14.0", default-features = false, features = ["serialize"] }
near-account-id = { version = "0.14", features = ["borsh", "serde"] }
near-sdk = "4.0"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
aurora-workspace-types = { path = ".", features = ["mock"] }
hex = "0.4.3"

[features]
mock = []
