[package]
name = "aurora-workspace-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum-types = { version = "0.14", default-features = false, features = ["serialize", "rlp"] }
near-sdk = "4.0"
near-account-id = "0.14"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
rlp = "0.5.1"

[dev-dependencies]
aurora-workspace-types = { path = ".", features = ["mock"] }
hex = "0.4.3"

[features]
deposit-withdraw = []
mock = []
