[package]
name = "aurora-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora-engine = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "745b0cc5f85432a421ba12b699e5e1cc12e3a6bb",  features = ["impl-serde"] }
aurora-engine-sdk = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "745b0cc5f85432a421ba12b699e5e1cc12e3a6bb" }
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", rev = "745b0cc5f85432a421ba12b699e5e1cc12e3a6bb",  features = ["impl-serde"] }
aurora-workspace-types = { path = "../workspace-types" }
borsh = { version = "0.9", default-features = false }
ethabi = { version = "17.2.0", optional = true }
ethereum-types = { version = "0.14", default-features = false, features = ["serialize"] }
lazy_static = "1.4"
near-primitives = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
workspaces = { git = "https://github.com/near/workspaces-rs.git", rev = "5311791a5a1654d1ba45fd318ed967abce25999d" }

[dev-dependencies]
aurora-workspace = { path = ".", features = ["mock"] }
anyhow = "1"
hex = "0.4.3"
tokio = { version = "1" }

[features]
default = []
eth-primitives = []
full-serde = []
# TODO: "mock" temporary until aurora-engine supports near_sdk
mock = []
